version: '3.3'
services:
    maccms:
        image: esme518/docker-maccms10
        container_name: maccms
        restart: always
        volumes:
            - ./data:/var/www/html
        ports:
            - 8084:80
    maccms-db:
        image: mariadb:10.3
        container_name: maccms-db
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 8085:3306
        environment:
            - MARIADB_ROOT_PASSWORD=DBPassword